DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS AUTHOR;

CREATE TABLE BOOK(ID INT PRIMARY KEY AUTO_INCREMENT,  NAME VARCHAR(255), GENRES VARCHAR(255), AUTHORS VARCHAR(255));
CREATE TABLE GENRE(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));
CREATE TABLE AUTHOR(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));