version: '2'
services:
  book-service:
    restart: always
    container_name: book-service
    image: book-service
    depends_on:
      - db
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=book
      - DATABASE_PORT=5432
  db:
    restart: always
    container_name: db
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=book
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    links:
      - book-service
    depends_on:
      - book-service
    ports:
      - 80:80
      - 444:443